### ISSUE TITLE
Extension not working on POP OS

### ISSUE THREAD

**Issue by igmriegel** [Maestroschan/appfolders-manager-gnome-extension#105]
Hello guys, would like to report that the estension is not working properly on POP OS:
_***GNOME Shell 3.36.4***_
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"

The issues are:
Clicking with rigth button does not show the options related to create os modify a folder;
I'm not sure, but it seens that it is crashing the app list when we acces the show applications on the dock.

I sincerely hope I'm helping you guys.

Thanks.

**Comment by maoschanz** [comment]
I've no idea why you want to patch GS 3.36.4 with this extension, but it makes no sense: managing appfolders is a native feature of GNOME Shell since a few years now, this extension was designed for older versions only.

The readme explicitly says:

>for GNOME Shell 3.28 to 3.32

and this information is written in the metadata too, and displayed on extensions.gnome.org

**Comment by igmriegel** [comment]
So, it's been a long time since your answer but I think I owe you an explanation...

Besides the fact that the feature of creating and managing appfolders is buil-in on the gnome 3.36 the distro I'm using, POP Os, comes with some default appfolders that we cant delete by default. The only way to do this is finding and editing manually the file that has this configuration wich is kind of hard to do.

Once again I want to thank you for your attention, and from now on if a Pop_Os user reaches you in this project he might be talking about the same thing as explained now.

Have a nice weekend!! 😃

**Comment by maoschanz** [comment]
there is no config file, it's in the dconf database. To edit it:

```sudo apt install dconf-editor```

then go here:

![Capture d’écran de 2020-12-04 17-19-54](https://user-images.githubusercontent.com/19996113/101187705-ffb2e900-3654-11eb-90c0-b0020f5b130b.png)

and remove the folder ids you don't want

----

but i remember that a few years ago there was an issue about Pop OS and its default appfolders, because they were recreated at each reboot or something like that, and that's their bug, no extension could fix this kind of absurd behavior

(i thought it was fixed though, so try to edit dconf first, and report to Pop OS if they come back)
