### ISSUE TITLE
add Rename Folder / Move Delete AppFolders only to AppFolders?

### ISSUE THREAD

**Issue by alex285** [Maestroschan/appfolders-manager-gnome-extension#16]
i know "renaming" is on Todo, but i open an issue because perhaps is the only "critical" issue i can find, apart some crashes that look random and i cannot reproduce

![bug-2](https://user-images.githubusercontent.com/11244308/26985196-20fe4b0a-4d4b-11e7-9ece-f727bb277b5f.png)

also can the "Delete Folder" moved on a menu on AppFolders? it makes more meaning, plus it removes one more item from the other menu, so it is nicer and faster (because less items) to use

**Comment by alex285** [comment]
actually these are two different bugs, but "Rename" should go again on appFolders only similar to "Remove" and not to appIcons

**Comment by maoschanz** [comment]
This idea has been planned since 2 weeks ("Rename" and "Delete" are already in all translation-related files) but i want the current version to be "stable" before i begin to do it.

The first issue i opened is a kind of "roadmap" where i note everything i try to do, every bug i notice, and features i plan to try

**Comment by maoschanz** [comment]
I have done a kind of "beta version" of this feature, however i don't totally understand signals for now so the extension does some funny (inoffensive) bugs

**Comment by alex285** [comment]
@Maestroschan it bugs, but i must say, amazing work!
