### ISSUE TITLE
An option for auto-arranging icons in folder, please!!!

### ISSUE THREAD

**Issue by Cookie74** [Maestroschan/appfolders-manager-gnome-extension#22]
An option for auto-arranging icons in folder, please. Not to get the icons all messed up.

**Comment by Cookie74** [comment]
Folders like games, internet, office.

**Comment by maoschanz** [comment]
You mean automatically doing folders by categories ? It's the next "milestone", it should be done next week

**Comment by Cookie74** [comment]
An option In the extension menu to organize the apps in folder automatically. 
example

![image](https://user-images.githubusercontent.com/30097589/28502971-e28714a0-6fd3-11e7-9e98-a8ea882a8339.png)


![image](https://user-images.githubusercontent.com/30097589/28503001-8c3d04a0-6fd4-11e7-9f9c-e8bb95422c7e.png)

**Comment by maoschanz** [comment]
Because of [this](https://github.com/Maestroschan/appfolders-manager-gnome-extension/issues/20), "an option in the preferences window" is not how i will implement it.

The right-click menu on an appfolder will show a "Add a category" submenu, and if a category is already set to a folder there will be a "Remove a category" submenu (it is the origin of ddnexus' issue: most distros have 2 folders by default, Sundry and Utilities, which don't directly contain apps, but only categories, that can't be removed by the extension for now).

I'm aware this is not a perfect way to do it (mainly because it means you have to create manually folders), but I prefer that the user can create/delete/remove what he want, and only what he want, and only when he explicitly want to do it. Especially, i can't just destroy existing settings during initialisation of the extension: in your mockup...
- if the "check button" is not clicked by default, it mean the extension should empty the 2 default appfolders without the approbation of the user.
- if it is clicked by default, it would mean creating folders without the approbation of the user.

**Comment by Warmuser** [comment]
There is another project: https://github.com/BenJetson/gnome-dash-fix

**Comment by maoschanz** [comment]
i kinda did it, it's on the official website
