### ISSUE TITLE
Where are the settings stored?

### ISSUE THREAD

**Issue by tiotrom** [Maestroschan/appfolders-manager-gnome-extension#69]
Hi! I have reinstalled my Linux and I do not know where the settings for this extension are stored, in order to restore them. I had lots of folders and and sorting. Cheers!

**Comment by maoschanz** [comment]
Like most GNOME software, it uses the dconf database. The paths of the settings in this database are settable with the `gsettings` command or with the "dconf-editor" app.

The extension itself has almost no settings: since the folders are a native GNOME Shell feature, the keys already exist in the dconf database even if the extension isn't installed (you can use shell scripts to automate their creation if you have multiple machines or sessions).

----

Paths using the dconf editor:

- `/org/gnome/desktop/app-folders/folder-children` contains a list of folder ids
- `/org/gnome/desktop/app-folders/folders/`[some folder id]`/name` contains the name of the folder
- `/org/gnome/desktop/app-folders/folders/`[some folder id]`/apps` contains a list of app launcher names (ending with `.desktop`)
- if you don't want to add each individual app to folders, it's more efficient to use categories: `/org/gnome/desktop/app-folders/folders/`[some folder id]`/categories` contains a list of categories (see the standard concerning app launcher categories [here](https://standards.freedesktop.org/menu-spec/latest/apa.html) and [here](https://standards.freedesktop.org/menu-spec/latest/apas02.html))

----

With the `gsettings` command and a "Games" folder, it's like

```bash
gsettings get org.gnome.desktop.app-folders folder-children
gsettings get org.gnome.desktop.app-folders.folder:/org/gnome/desktop/app-folders/folders/Games/ name
gsettings get org.gnome.desktop.app-folders.folder:/org/gnome/desktop/app-folders/folders/Games/ apps
gsettings get org.gnome.desktop.app-folders.folder:/org/gnome/desktop/app-folders/folders/Games/ categories
```
```bash
gsettings set org.gnome.desktop.app-folders folder-children ['Whatever', 'Sundry', 'Games']
gsettings set org.gnome.desktop.app-folders.folder:/org/gnome/desktop/app-folders/folders/Games/ name 'Games'
#gsettings set org.gnome.desktop.app-folders.folder:/org/gnome/desktop/app-folders/folders/Games/ apps [] # useless here
gsettings set org.gnome.desktop.app-folders.folder:/org/gnome/desktop/app-folders/folders/Games/ categories ['Game']
```
